# references
# https://github.com/jkeylu/deploy-hexo-site-by-travis-ci
# https://github.com/yous/yous.github.io/blob/source/.travis.yml

language: node_js
branches:
  only:
  - master
before_script:
- git config --global user.name 'regrex'
- git config --global user.email 'dengxi.daisy@gmail.com'
after_success:
- git clone --depth 1 --branch gh-pages --single-branch $GH_TOKEN . || (git init && git remote add -t gh-pages origin $GH_TOKEN)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m "site updated via travis-ci at $(date -u +'%Y-%m-%d %H:%M:%S') $TRAVIS_COMMIT"
- git branch -m master
- git push -q $GH_TOKEN HEAD:master
